movieproject/movieapp/urls.py
from .import views
from django.urls import path
app_name = 'movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from  . forms import MovieForm
# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list':movie
    }
    return render(request,"index.html" , context)

def detail(request,movie_id):
    fetch =Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'obj':fetch})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,img=img,year=year)
        movie.save()

    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'obj1':movie,'obj2':form})

def delete(request,id):
    if request.method=='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <fieldset>

        <legend>MOVIE INFORMATON</legend>

<p>
    <label for="name">Name</label>
    <input type="text" id="name" name="name" placeholder="Enter Movie Name">
</p>

    <p>
     <label for="desc">Description</label>
    <input type="text" id="desc" name="desc" placeholder="Enter Movie Description">
        </p>
    <p>
        <label for="year">Year</label>
    <input type="number" id="year" name="year" placeholder="Enter Year"  min="1950" max="2023" step="1" value="2023" >
    </p>
    <p>
        <label for="img">Image</label>
        <input type="file" id="img" name="img">
    </p>
        <p>
            <input type="submit">
        </p>


     </fieldset>
</form>

</body>
</html>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">

</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    MOVIE APP
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>delete</title>
</head>
<body>
<form method="post">
     {% csrf_token %}
<h1>do you want to delete this ???</h1>
     <input type="submit">
</form>
</body>
</html>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ obj.img.url}}" width="300" height="280">

        </div>
        <div class="col-md-6">
            <h2>{{obj.name}}</h2><br>
           <h3>{{obj.desc}}</h3><br>
            <h3>On Theaters : {{obj.year}}</h3><br>

           <a  class = "btn btn-warning"href  ="{% url 'movieapp:update' obj.id %}">UPDATE</a>
            <a  class = "btn btn-danger"href  ="{% url 'movieapp:delete' obj.id %}">DELETE</a>

        </div>



{% endblock %}


    </div>

</div>

movieproject/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{obj2.as_p}}
    
    <p>
        <input type="submit">
    </p>
</form>
</body>
</html>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img style="width=100px;height=100px" class="card-img-top" src="{{ i.img.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">DETAILS</a>
  </div>
</div>


        </div>
        {% endfor %}

    </div>

</div>




{% endblock %}